### ISSUE TITLE
The shipping method is too long and has underscore make magento cant recognize the shipping method when checkout 

### ISSUE THREAD

**Issue by a970032** [Smile-SA/elasticsuite-for-retailer#7] opened 2017-11-24 09:15 UTC
checkout page throw Please specify a shipping method

The shipping method is too long and has underscore make magento cant recognize the shipping method when checkout 

if i replace all smile_store_delivery with smilestoredelivery and problem is temp fixed but the name is still too long it may broke magento checkout

**Comment by romainruaud** [comment] 2017-11-24 09:17
Hello @a970032 which version of Magento are you using ?

There was a problem in Magento 2.1 with the shipping_method field that was too long. It has been fixed in the module but I did not test it again against Magento 2.2.

Regards

**Comment by a970032** [comment] 2017-11-24 09:21
i am using it in Magento 2.2 after the replacing all smile_store_delivery with smilestoredelivery. i can checkout but the shipping method is switched to checkout and money order i dont know is it a magento bug or not

**Comment by romainruaud** [comment] 2017-11-24 09:27
Okay,

we'll have a look on Magento 2.2 with this module since it's untested for now. We put the effort on the elasticsuite module first, and will now ensure this one is also compatible.

Best regards.

**Comment by a970032** [comment] 2017-11-24 09:28
Thanks for the quick reply

**Comment by romainruaud** [comment] 2017-11-29 11:03
Hello @a970032 I think I have understood...

Could you please copy paste here what does the output of "describe sales_order" and "describe quote_address" in you MySQL server ?

You should see the field "shipping_method" with a length of 120 chars.

But I'm pretty sure you will not... If I take a look to this Magento's commit : https://github.com/magento/magento2/commit/f70b196d2d534d0587dffa718e5cf3e111fcfc0c

I'm pretty sure that since they did put it only in an "UpgradeSchema", it is triggered *only when upgrading* an existing version of Magento, and it is *not ran when installing Magento 2.2 from scratch*.

I did backport the same fix in our module here : https://github.com/Smile-SA/magento2-module-store-delivery/blob/master/Setup/InstallSchema.php#L47

But I was expecting Magento doing their job properly and updating the column *in Install AND Upgrade*, which does not seem to be the case ...

Can you confirm the shipping method field is not 120 characters length as expected when installing Magento 2.2 from scratch ?

Regards

**Comment by a970032** [comment] 2017-11-29 11:19
I see the shipping_method length in sales_order is 120 length 
so the problem i guess is the way magento split the shipping method they using 
list($carrierCode, $method) = explode('_', $shippingMethod, 2);
so if your shipping method contain underscore will fail
here some class i found :
vendor\magento\module-sales\Model\Order.php:1194 getShippingMethod()
vendor\magento\module-rma\Model\Shipping.php::326

**Comment by romainruaud** [comment] 2017-11-29 11:30
Well that's kinda strange, I am not able to reproduce your issue on my instance.

What is the exact version of Magento you are using ? and is it a CE or EE version ?

Regards

**Comment by romainruaud** [comment] 2017-11-29 11:31
Are you able to record what is happening ? I do no understand very well at which step of the checkout you are getting the error.

Best regards

**Comment by a970032** [comment] 2017-11-30 03:02
i have tested it should be fine on guest checkout but not with member logged in 
enclose the video 
ew file is too big so i uploaded to youtube
https://www.youtube.com/watch?v=mH99Ermj9zI&feature=youtu.be

**Comment by a970032** [comment] 2017-11-30 03:05
i have created another video guest checkout
https://youtu.be/87qZVtYl9RM

**Comment by a970032** [comment] 2017-11-30 03:10
and i have seen some post on stackoverflow about the underscore problem 
https://stackoverflow.com/questions/21470816/after-creation-of-custom-shipping-method-the-getshippingcarrier-function-retur/23620361

**Comment by a970032** [comment] 2017-11-30 03:16
After i global replace 
![image](https://user-images.githubusercontent.com/18587853/33411317-db291148-d5bf-11e7-9d73-d328f0dbe2c9.png) like this and the missing firstname lastname telephone and shipping method is also solved

**Comment by romainruaud** [comment] 2018-01-25 12:25
Confirmed.

I just faced it on my instance. However this seems to appear only when logged in, when guest checkout goes fine.

Really strange... But I will fix this one.

Regards

**Comment by romainruaud** [comment] 2018-01-25 13:41
This one has been fixed in latest version of StoreDelivery module.

Let me know

**Closed by romainruaud** 2018-01-25 13:41 UTC
Labels: bug
